name: rodalies_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - statsmodels
  - scipy
  - jupyterlab
  - pyarrow
  - tqdm
  - pip
  - pip:
      - arch
      - google-auth
      - google-auth-oauthlib
      - google-auth-httplib2
      - google-api-python-client
